### ISSUE TITLE
Two fields in the same row

### ISSUE THREAD

**Issue by forgecodex** [lahirulhr/nova-lock-screen#1]
can you do a like this  https://camo.githubusercontent.com/7a7aaa5505a5361cd3afd8a14b54b92952867e43f504af57538a1316e19628e2/68747470733a2f2f692e696d6775722e636f6d2f373733644853742e706e67

**Comment by lahirulhr** [comment]
Hi. I hope you are not asking about nova-lock-screen package. Right ?

**Comment by lahirulhr** [comment]
Not relevant
