### ISSUE TITLE
Class "Lahirulhr\NovaLockScreen\NovaLockScreen" not found

### ISSUE THREAD

**Issue by makowskid** [lahirulhr/nova-lock-screen#2]
I keep getting this error with the default configuration steps provided in the manual.
Cache cleared.
PHP 8.2.8
Laravel 10.21.0

I will solve it eventually, but there might be a problem with loading a Tool inside `NovaServiceProvider` - you might want to take a look, especially that composer complains:
```
Class Lahirulhr\NovaLockScreen\NovaLockScreen located in ./vendor/lahirulhr/nova-lock-screen/src/NovaLockscreen.php does not comply with psr-4 autoloading standard. Skipping.
```

**Comment by lahirulhr** [comment]
Thank you for reporting the issue. fixed !

**Comment by makowskid** [comment]
Thanks!
