### ISSUE TITLE
How to change url of this lockscreen?

### ISSUE THREAD

**Issue by superuser-me** [lahirulhr/nova-lock-screen#4]
It's working perfectly fine but 
how can i change the url of lock screen page?
currently it's default /admin/nova-lock-screen

**Comment by lahirulhr** [comment]
setting custom url is currently not available. but nice to have. i'll add this feature on next release

**Comment by lahirulhr** [comment]
Locking url is now configurable using config file

**Comment by superuser-me** [comment]
Thank you 🙏
